# Build static site for GitHub Pages (_site/)
param(
    [string]$HubApi = $env:HUB_API,
    [string]$HubToken = $env:HUB_TOKEN,
    [string]$HubBase = $env:HUB_BASE
)

$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
$site = Join-Path $root '_site'
$static = Join-Path $root 'static'

if (-not $HubBase) {
    $repo = $env:GITHUB_REPOSITORY
    if ($repo -and $repo -notmatch '\.github\.io$') {
        $name = ($repo -split '/')[1]
        if ($name) { $HubBase = "/$name" }
    }
}

if (Test-Path $site) { Remove-Item $site -Recurse -Force }
New-Item -ItemType Directory -Path (Join-Path $site 'static') -Force | Out-Null

Copy-Item -Path (Join-Path $static '*') -Destination (Join-Path $site 'static') -Recurse -Force
Copy-Item -Path (Join-Path $static 'index.html') -Destination (Join-Path $site 'index.html') -Force

$apiJs = if ($HubApi) { "'$($HubApi -replace "'", "\\'")'" } else { "''" }
$tokenJs = if ($HubToken) { "'$($HubToken -replace "'", "\\'")'" } else { "''" }
$baseJs = if ($HubBase) { "'$($HubBase -replace "'", "\\'")'" } else { "''" }

$config = @"
/* Generated by prepare-pages.ps1 — do not edit on Pages */
window.__HUB_API__ = $apiJs;
window.__HUB_TOKEN__ = $tokenJs;
window.__HUB_BASE__ = $baseJs;
"@

Set-Content -Path (Join-Path $site 'static/hub-config.js') -Value $config -Encoding UTF8
Write-Host "Pages site ready: $site (HUB_BASE=$HubBase, HUB_API=$HubApi)"